package main

import (
	"encoding/csv"
	"fmt"
	"log"
	"os"
	"strings"
	"time"

	"golang.org/x/text/encoding/japanese"
	"golang.org/x/text/transform"
)

func main() {
	// 元となるUTF-8のCSVファイル
	csvFile := "syukujitsu.csv"
	// 出力先の自動生成Goソースファイル
	outFile := "syukujitsu_data.go"

	f, err := os.Open(csvFile)
	if err != nil {
		log.Fatalf("CSVを開けませんでした: %v", err)
	}
	defer f.Close()

	// Shift_JIS から UTF-8 への変換リーダーを挟む
	sjisReader := transform.NewReader(f, japanese.ShiftJIS.NewDecoder())
	r := csv.NewReader(sjisReader)
	records, err := r.ReadAll()
	if err != nil {
		log.Fatalf("CSVの読み込みに失敗しました: %v", err)
	}

	// 「今年」の年を取得（これ以降を含める）
	currentYear := time.Now().Year()

	var lines []string
	lines = append(lines, "// Code generated by tools/csv2go/main.go; DO NOT EDIT.")
	lines = append(lines, "package main\n")
	lines = append(lines, "var syukujitsuMap = map[string]struct{}{")

	count := 0
	for i, record := range records {
		if i == 0 {
			continue // ヘッダー行をスキップ
		}
		if len(record) < 2 {
			continue
		}

		dateStr := record[0] // 例: "2024/1/1" または "2024/01/01"

		// YYYY/MM/DD 系をパース
		// フォーマット揺れを吸収するため、スラッシュをハイフンにして time.Parse で確認
		dateStr = strings.ReplaceAll(dateStr, "/", "-")
		
		// 形式は "2006-1-2", "2006-01-02" など様々考えられるため、手動でパース
		parts := strings.Split(dateStr, "-")
		if len(parts) != 3 {
			continue
		}
		
		var year, month, day int
		fmt.Sscanf(parts[0], "%d", &year)
		fmt.Sscanf(parts[1], "%d", &month)
		fmt.Sscanf(parts[2], "%d", &day)

		// 実行年より過去の祝日データは除外
		if year < currentYear {
			continue
		}

		formattedDate := fmt.Sprintf("%04d-%02d-%02d", year, month, day)

		// `"2026-01-01": {}, // 元日` の形式で出力内容を構成
		lines = append(lines, fmt.Sprintf("\t%q: {}, // %s", formattedDate, record[1]))
		count++
	}

	lines = append(lines, "}\n")

	outContent := strings.Join(lines, "\n")
	err = os.WriteFile(outFile, []byte(outContent), 0644)
	if err != nil {
		log.Fatalf("Goソースファイルの書き込みに失敗しました: %v", err)
	}

	fmt.Printf("成功: %d件の祝日データを %s に生成しました。\n", count, outFile)
}
