package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"log"
	"os"
	"strings"
	"time"

	"golang.org/x/text/encoding/japanese"
	"golang.org/x/text/transform"
)

const (
	defaultInput  = "syukujitsu.csv"
	defaultOutput = "internal/businessday/syukujitsu_data.go"
)

func main() {
	inPath := flag.String("in", defaultInput, "入力元のCSVファイルパス")
	outPath := flag.String("out", defaultOutput, "出力先のGoソースファイルパス")
	flag.Parse()

	count, err := run(*inPath, *outPath)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("成功: %d件の祝日データを %s に生成しました。\n", count, *outPath)
}

func run(inPath, outPath string) (int, error) {
	f, err := os.Open(inPath)
	if err != nil {
		return 0, fmt.Errorf("CSVを開けませんでした: %w", err)
	}
	defer f.Close()

	// Shift_JIS から UTF-8 への変換リーダーを挟む
	sjisReader := transform.NewReader(f, japanese.ShiftJIS.NewDecoder())
	r := csv.NewReader(sjisReader)
	records, err := r.ReadAll()
	if err != nil {
		return 0, fmt.Errorf("CSVの読み込みに失敗しました: %w", err)
	}

	// 「今年」の年を取得（これ以降を含める）
	currentYear := time.Now().Year()

	var entries []string
	for i, record := range records {
		if i == 0 {
			continue // ヘッダー行をスキップ
		}
		if len(record) < 2 {
			continue
		}

		parsed, err := parseHolidayDate(record[0])
		if err != nil {
			log.Printf("警告: 日付を解釈できずスキップしました (行 %d: %q): %v", i+1, record[0], err)
			continue
		}

		// 実行年より過去の祝日データは除外
		if parsed.Year() < currentYear {
			continue
		}

		formattedDate := parsed.Format("2006-01-02")

		// `"2026-01-01": {}, // 元日` の形式で出力内容を構成
		entries = append(entries, fmt.Sprintf("\t%q: {}, // %s", formattedDate, record[1]))
	}

	outContent := generateSource(entries)
	if err := os.WriteFile(outPath, []byte(outContent), 0644); err != nil {
		return 0, fmt.Errorf("Goソースファイルの書き込みに失敗しました: %w", err)
	}

	return len(entries), nil
}

// parseHolidayDate は "2026/1/1" や "2026/01/01" 形式の日付文字列をパースします
func parseHolidayDate(s string) (time.Time, error) {
	return time.Parse("2006/1/2", s)
}

func generateSource(entries []string) string {
	var lines []string
	lines = append(lines, "// Code generated by tools/csv2go/main.go; DO NOT EDIT.")
	lines = append(lines, "package businessday\n")
	lines = append(lines, "var syukujitsuMap = map[string]struct{}{")
	lines = append(lines, entries...)
	lines = append(lines, "}\n")

	return strings.Join(lines, "\n")
}
